core/urls.py
from django.conf.urls import patterns, url
from views import RegistrationView

urlpatterns = patterns('',

    url(r'^$', 'core.views.cards', name='cards'),
    url(r'^login/$', 'core.views.custom_login', name='login'),
    url(r'^sign_in/$', 'django.contrib.auth.views.login'),
    url('^register/', RegistrationView.as_view(), name='register'),
    url(r'^rounds/$', 'core.views.next_round', name='rounds'),
    url(r'^results/$', 'core.views.results', name='results'),
    url(r'^metrics/$', 'core.views.metrics', name='metrics'),
    url(r'^ajax_suggestion/$', 'core.views.ajax_suggestion', name='ajax_suggestion'),
    url(r'^encountered/$', 'core.views.encountered', name='encountered'),
    url(r'^globally_known/$', 'core.views.globally_known', name='globally_known'),

)

face_off/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()
admin.site.site_header = "Excella Face It Administration"
admin.site.site_title = "Excella Face It"

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'', include('core.urls', namespace='core')),
                       url('', include('social.apps.django_app.urls', namespace='social')),
                       url('', include('django.contrib.auth.urls', namespace='auth')),
                       url(r'^s3direct/', include('s3direct.urls')),
                      )

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from s3direct.fields import S3DirectField

# App specific user model
class UserProfile(AbstractUser):
    # The additional attributes we wish to include.
    yammer_url = models.URLField(blank=True)
    upload_image_url = models.URLField(blank=True)
    network = models.CharField(max_length=50)
    upload_img_file = S3DirectField(dest='imgs', blank=True, null=True)
    is_custom_user = models.BooleanField(blank=True, default=False)

    def __unicode__(self):
        return self.username


class UserMetrics(models.Model):
    user = models.ForeignKey(UserProfile, unique=True, related_name='user')

    times_won = models.IntegerField(blank=True, default=0)
    times_known = models.IntegerField(blank=True, default=0)

    class Meta:
        ordering = ["user__last_name"]
        verbose_name = "User Metric"
        verbose_name_plural = "User Metrics"

    def __unicode__(self):
        return self.user.get_full_name() + " - lifetime points: " + str(self.times_won)


class ColleagueGraph(models.Model):
    user = models.ForeignKey(UserProfile, related_name='user_colleague_graph')

    yammer_id = models.IntegerField(default=0)
    name = models.CharField(max_length=200, blank=True)
    img_url = models.URLField(blank=True)
    yammer_url = models.URLField(blank=True)
    times_correct = models.IntegerField(blank=True, default=0)
    times_incorrect = models.IntegerField(blank=True, default=0)

    class Meta:
        ordering = ["user__id"]
        verbose_name = "Graph of Known Colleagues"
        verbose_name_plural = "Graphs of Known Colleagues"

    # Renamed for admin page usage
    def __unicode__(self):
        return self.name


class MostKnown(models.Model):
    most_known_colleague = models.CharField(max_length=200, blank=True)
    # Timestamp for each entry for historical graphing
    date_time = models.DateField('Timestamp')

    class Meta:
        verbose_name = "Most known Colleague"
        verbose_name_plural = "Most known Colleagues"


class GlobalMetrics(models.Model):
    network = models.CharField(max_length=200, blank=True, unique=True)
    most_known = models.ForeignKey(MostKnown)

    class Meta:
        verbose_name = "Global Metric"
        verbose_name_plural = "Global Metrics"


class Suggestions(models.Model):
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    email = models.EmailField(blank=False)
    suggestion = models.TextField(max_length=500, blank=False)

    def __unicode__(self):
        return self.suggestion

    class Meta:
        verbose_name = "Suggestion"
        verbose_name_plural = "Suggestions"

core/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML, Div
from crispy_forms.bootstrap import FormActions
from core.models import Suggestions, UserProfile

class UserAuthenticationForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)

    def __init__(self, *args, **kwargs):
        super(UserAuthenticationForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout()

        self.helper.layout.append(Div('username'))
        self.helper.layout.append(Div('password'))

        self.helper.layout.append(FormActions(
            Submit('Submit', 'Submit', css_class='btn btn-primary pull-right'),
            HTML("<button id=\"close\" type=\"button\" class=\"btn btn-default pull-right\" data-dismiss=\"modal\">Close</button>"),
        ))

    def save(self):
        user = super(UserAuthenticationForm, self)
        user.save()
        return user

class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        # self.fields['upload_img_file'] = forms.URLField(widget=S3DirectWidget(dest='img'))
        self.fields['upload_img_file'].label = 'Profile Image'
        self.fields['upload_img_file'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

        self.helper.layout.append(FormActions(
            Submit('Submit', 'Submit'),
        ))

    class Meta:
        model = UserProfile
        fields = ('username', 'first_name', 'last_name', 'password', 'upload_img_file')


class SuggestionForm(forms.ModelForm):
    class Meta:
        model = Suggestions
        fields = ('first_name', 'last_name', 'email', 'suggestion')


class ResultForm(forms.Form):
    score = forms.IntegerField(widget=forms.HiddenInput())
    answer_id = forms.IntegerField(widget=forms.HiddenInput())
    results = forms.CharField(widget=forms.HiddenInput())
    correct = forms.CharField(widget=forms.HiddenInput())
    mode = forms.CharField(widget=forms.HiddenInput())

core/views.py
import requests, re, ast, random, HTMLParser, json
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django_redis import get_redis_connection
from core.models import UserMetrics, ColleagueGraph
from django.core.exceptions import ObjectDoesNotExist
from core.forms import SuggestionForm, ResultForm, UserProfileForm, UserAuthenticationForm
from django.views.generic import CreateView
import django.contrib.auth.views
from django.contrib.auth import authenticate, login
from django.conf import settings

class RegistrationView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserProfileForm
    success_url = '/'

    def get_success_url(self):
        user = self.object
        user.set_password(user.password)
        user.is_custom_user = True
        user.save()

        return '/'



def custom_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    elif request.method == 'POST':
        form = UserAuthenticationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            username = data['username']
            password = data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')

    return django.contrib.auth.views.login(request, extra_context={'userAuthForm': UserAuthenticationForm()})

@login_required()
def cards(request):
    redis_con = get_redis_connection("default")

    # Yammer Authenticated Game
    if not request.user.is_custom_user:
        if request.user.email:
            network = str(request.user.email.split('@')[1]) + '_users'
        else:
            network = 'default_users'

        if not redis_con.exists(network):
            users = yammer_user_restcall(request)
            load_users_to_cache(redis_con, users, network)

        user_round_matrix = [four_random_cards(redis_con, network, request.user) for x in range(5)]
        answer = random.choice(user_round_matrix[0])
        stars = []

        context = RequestContext(request, {'cards': user_round_matrix, 'answer': answer,
                                           'round': 0, 'score': 0, 'stars': stars})
        return render_to_response('game.html', context_instance=context)
    else:
        context = RequestContext(request)
        return render_to_response('custom_game.html', context)


@login_required
def next_round(request):
    round_num = int(request.POST['round'])
    score = int(request.POST['score'])
    answer_id = int(request.POST['answer_id'])
    correct = ast.literal_eval(str(request.POST['correct']))
    stars = request.POST.getlist('stars[]')
    stars.append(str(correct))
    stars = json.dumps(stars)


    card_matrix = HTMLParser.HTMLParser().unescape(request.POST['matrix'])
    card_matrix = ast.literal_eval(card_matrix)

    # Sets the Winner of the round to the cardMatrix
    update_results_list(card_matrix, answer_id, round_num, correct)

    # Prepares data for next round
    round_num += 1
    answer = filter_previously_used_answer(card_matrix, round_num)


    context = RequestContext(request, {'cards': card_matrix, 'round': round_num, 'answer': answer,
                                       'score': score, 'stars': stars, 'resultsForm': ResultForm()})

    return render_to_response('cards.html', context_instance=context)


@login_required
def results(request):
    metric = UserMetrics.objects.get(user=request.user)

    if request.method == 'POST':
        form = ResultForm(request.POST)
        if form.is_valid():
            results = ast.literal_eval(HTMLParser.HTMLParser().unescape(form.cleaned_data['results']))
            answer_id = form.cleaned_data['answer_id']
            correct = ast.literal_eval(str(form.cleaned_data['correct']))
            update_results_list(results, answer_id, 4, correct)  # 4 representing the last round (zero-based)

            if form.cleaned_data['mode'] != 'easy':
                metric.times_won = form.cleaned_data['score']
                metric.save()
                save_metric_results(results, request.user)

            context = RequestContext(request, {'score': form.cleaned_data['score'], 'cards': results})
            return render_to_response('results.html', context_instance=context)


@login_required
def metrics(request):
     # Colleagues you should get to know
    most_incorrect_colleagues = ColleagueGraph.objects.order_by('-times_incorrect').filter(user=request.user)[:5]

    context = RequestContext(request, {'leastknown': most_incorrect_colleagues})

    return render_to_response('metrics.html', context_instance=context)

@login_required
def encountered(request):
    # Colleagues Encountered Data
    encountered = ColleagueGraph.objects.filter(user=request.user).order_by('name')
    correct_arr = []
    incorrect_arr = []
    for colleague in encountered:
        correct_arr.append({"label": str(colleague.name), "value": colleague.times_correct})
        incorrect_arr.append({"label": str(colleague.name), "value": (colleague.times_incorrect * -1)})

    times_known = {"key": "Guessed Correctly", "color": 'red', "values": correct_arr}
    times_not_known = {"key": "Guessed Incorrectly", "color": "blue", "values": incorrect_arr}
    jsondata = [times_known, times_not_known]

    return HttpResponse(json.dumps(jsondata), content_type="application/json")

@login_required
def globally_known(request):
    # Global Known Colleagues
    globally_known = globally_known_colleagues()
    names = []
    times_correct = []

    for metric in globally_known:
        names.append(str(metric.name))
        times_correct.append(metric.times_correct)

    known = {
        'names': names,
        'times_correct': times_correct
    }
    return HttpResponse(json.dumps(known), content_type="application/json")

# Helper Functions
def yammer_user_restcall(request):
    users = []
    social = request.user.social_auth.get(provider='yammer')
    access_token = social.extra_data['access_token']
    page = 1

    while True:
        response = requests.get(
            'https://www.yammer.com/api/v1/users.json?page=%d' % page,
            headers={'Authorization': 'Bearer %s' % access_token['token']}
        )
        if not response.json():
            break
        users.extend(response.json())
        page += 1

    return users


def load_users_to_cache(redis_con, users, network):
    pattern = re.compile('.+no_photo.png$')  # Filters out users with no photo
    for user in users:
        if not pattern.match(user['mugshot_url']):
            redis_con.sadd(network, {
                'id': user['id'],
                'name': user['full_name'],
                'mugshot': user['mugshot_url_template'],
                'user_url': user['web_url'],
                'network': user['network_name'],
            })
    redis_con.expire(network, 43200)  # Redis cache expiration set to 12hrs(43200s)


def filter_previously_used_answer(card_matrix, round):
    answer = random.choice(card_matrix[round])
    unique_answer = False
    # Checks for previously used answer
    while not unique_answer:
        check_again = False
        for i in range(0, round):
            if card_matrix[i]['id'] == answer['id']:
                answer = random.choice(card_matrix[round])
                check_again = True
                break

        if not check_again:
            unique_answer = True

    return answer


def save_metric_results(results, user):
    for result in results:
        if result:
            try:
                metric = ColleagueGraph.objects.get(user=user, yammer_id=result['id'])
            except ObjectDoesNotExist:
                metric = ColleagueGraph.objects.create(user=user, yammer_id=result['id'],
                                                       name=result['name'], img_url=result['mugshot'],
                                                       yammer_url=result['user_url'])
            finally:
                if 'wrong' in result:
                    metric.times_incorrect += 1
                else:
                    metric.times_correct += 1
                metric.save()


def update_results_list(card_matrix, answer_id, round, correct):
    for i in range(0, 4):
        if card_matrix[round][i]['id'] == answer_id:
            if not correct:
                card_matrix[round][i]['wrong'] = True
                card_matrix[round] = card_matrix[round][i]
            else:
                card_matrix[round] = card_matrix[round][i]

            return card_matrix


def four_random_cards(redis_con, network, current_user):
    users = []

    while len(users) < 4:
        val = ast.literal_eval(redis_con.srandmember(network))
        if current_user.get_full_name() != val['name'] and val not in users:
            users.append(val)

    return users


def globally_known_colleagues():
    top_scores = (ColleagueGraph.objects.order_by('-times_correct')
                  .values_list('times_correct', flat=True)
                  .distinct())[:10]

    filtered_by_name = (ColleagueGraph.objects.order_by('name', '-times_correct')
                .filter(times_correct__in=top_scores))\
                .distinct('name')

    top_10_known_colleagues = sorted(filtered_by_name,
                                     key=lambda ColleagueGraph: ColleagueGraph.times_correct,
                                     reverse=True)[:10]
    return top_10_known_colleagues


def ajax_suggestion(request):
    if request.method == 'POST' and request.is_ajax():
        form = SuggestionForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

core/templates/base.html
<!doctype html>
{% load replace %}
{% load staticfiles %}
{% load pipeline %}

{% comment %} paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ {% endcomment %}
<!--[if lt IE 7]> <html class="lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie10 lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie10 lt-ie9" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="lt-ie10" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}Face Off{% endblock %}</title>
    {% comment %} Core CSS includes (for inclusion on all pages) {% endcomment %}
    {% stylesheet 'css' %}
    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static "js/util.min.js" %}"></script>
    <script type="text/javascript" data-app-id="{{ app_id }}" src="{% static "js/yammer_sdk.min.js" %}"></script>
    <script>
        function yammerLogout() {
            yam.logout(function (response) {
                window.location.href = "{% url 'auth:logout' %}?next={{ request.path }}";
            })
        }
    </script>
    {% comment %}
        Per-page CSS is compressed separately so that the global stuff doesn't get re-downloaded each time
    {% endcomment %}
    {% block extra_js_css %}{% endblock %}
</head>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <a class="navbar-brand" href="{% url 'core:cards' %}">{{ request.user.network|capfirst|replace:"/.com/" }} Face
        Off</a>

    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
            {% if request.user.is_authenticated and not request.user.is_custom_user %}

                <li><img src='{{ user.yammer_url|replace:"/{width}/70"|replace:"/{height}/70" }}'></li>
                <li><a id="userName">{{ request.user.get_full_name }}</a></li>
            {% elif request.user.is_authenticated and request.user.is_custom_user %}
                <li><img src='{{ user.upload_img_file }}' style="width:70px;height:70px"></li>
                <li><a id="userName">{{ request.user.get_full_name }}</a></li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li><a class="btn" id="logout" onclick="yammerLogout()">Logout</a></li>
                <li><a></a></li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-left">
            {% if not request.user.is_authenticated %}
                <li style="display:none"><a class="btn btn-default" name="register" href="{% url 'core:register' %}"
                   style="padding:20px;">Register
                </a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<body>
<div class="container">
    {% block content %} {% endblock %}
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">© 2015 Excella, All Rights Reserved</p>
        <ul class="pull-right list-inline">
            <li>
                <a href="https://github.com/excellaco/face_it">GitHub Project</a>
            </li>
            <li>
                <a href="https://github.com/excellaco/face_it/issues">Issues</a>
            </li>
            <li>
                {% include 'suggestion.html' %}
                <a href="#form" data-toggle="modal">Suggestion</a>
            </li>
        </ul>
    </div>
</footer>

{% comment %}
    JavaScript at the bottom for fast page loading:
    http://developer.yahoo.com/performance/rules.html#js_bottom
{% endcomment %}

<!-- compressed tags is created by Django Pipeline. -->
{% javascript 'js' %}

{% block extra_js %}{% endblock %}
</body>
</html>

core/templates/cards.html
{% load replace %}
{% load resolve %}
{% load static %}


<div class="page-header" id="banner">
    <div class="row" id="gameHeader">
        <h3 id="easyHeader" class="pull-left" style="margin-top: 3%; margin-left: 0%;"> Practice Mode</h3>
        <h3 id="hardHeader" class="pull-left" style="margin-top: 3%; margin-left: 0%;"> Competitive Mode</h3>
    </div>
</div>

{% with cards|resolve:round as list %}
    {% for card in list %}
        <div id="colleague{{ forloop.counter0 }}" class="flip-container"
             onclick="flip('{{ forloop.counter0 }}', '{{ card.id }}')">
            <div class="flipper">
                <li class="no-bullets">
                    <div class="front">
                            <a href="#" class="thumbnail">
                                <img src='{{ card.mugshot|replace:"/{width}/256"|replace:"/{height}/256"}}'>
                            </a>
                    </div>
                    {% if answer.id == card.id %}
                        <div class="back panel panel-success cardpanel">
                            <div class="panel-heading"><h4></h4></div>
                            <div class="panel-body">
                                <div class="resizableText">
                                    <span>{{ card.name }}</span>
                                </div>
                                <h1><i class="fa fa-check-circle-o fa-6"></i></h1>
                            </div>
                        <div style="margin-bottom: 100%; margin-left: 75%" >
                            <i id="turnFlag {{ forloop.counter0 }}" class="fa fa-share fa-2x" ></i>
                        </div>
                        </div>
                    {% else %}
                        <div class="back panel panel-danger cardpanel">
                            <div class="panel-heading"><h4></h4></div>
                            <div class="panel-body">
                                <div class="resizableText">
                                    <span>{{ card.name }}</span>
                                </div>
                                <h1><i class="fa fa-times-circle-o fa-6"></i></h1>
                            </div>
                        <div style="margin-bottom: 100%; margin-left: 75%">
                            <i id="turnFlag {{ forloop.counter0 }}" class="fa fa-share fa-2x" ></i>
                        </div>
                        </div>
                    {% endif %}
                </li>
            </div>
        </div>
    {% endfor %}
{% endwith %}
<div class="row" align="center">
    <h2 style="width: 50%;">Who is {{ answer.name }}? </h2>
    <div class="row">
</div>
<div class="row">
    <h2 id="stars" style="float: left; width: 30%;"></h2>
    <div style="float: right; width: 30%;" id="countdown"></div>
    <div style="float: right; width:30%;" id="nextRoundCountdown"></div>
    <button  id="nextRound" onclick="nextRound()" class="btn btn-primary invisible" style="width: 160px; height: 60px; margin-right: 30%">
        Next
        Round
    </button>
</div>

<ul class="text-center">
    <form id="resultsForm" action="{% url 'core:results' %}" method="post">
        {% csrf_token %}
        {{ resultsForm }}
        <input id="resultsSubmit" type="submit" onclick="setForm()" class="btn btn-primary invisible" value="Results"
               style="width: 160px; height: 60px"/>
    </form>
</ul>


<div style="margin-right: 12%" id="startGameModal" class="modal fade" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Face Off</h4>
            </div>
            {% if '/no_photo.png' in request.user.yammer_url %}
                <div class="modal-body">
                    <div id="noPicText" class="">
                        <p class="text">Hey, {{ request.user.get_full_name }}! Click <a id="noPicLink"
                                href="{{ request.user.upload_image_url }}">here</a>
                            to upload an image and become part of the game!
                        </p>
                    </div>
                    <div id="addGameText" class="invisible">
                        <p class="text"> Get ready to play! The clock starts when
                            you select your mode!</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <div id="noPicMenu" class="">
                        <button id="noPicButton" value="I don't care" onclick="showGameMenu()" class="btn btn-primary btn-block">I don't care
                            <i class="fa fa-meh-o"></i></button>
                        <a class="btn btn-default btn-block" onclick="yammerLogout()">Logout</a>
                    </div>
                    <div id="gameMenu" class="invisible">
                        <button type="button" id="easyGame" onclick="startEasyGame()" class="btn btn-primary btn-block"
                                data-dismiss="modal">Practice Mode
                        </button>
                        <button type="button" id="hardGame" onclick="startHardGame()" class="btn btn-primary btn-block"
                                data-dismiss="modal">Race against the Clock!
                        </button>
                        <a class="btn btn-default btn-block" onclick="yammerLogout()">Logout</a>
                    </div>
                </div>
            {% elif '/no_photo.png' not in request.user.yammer_url %}
                <div class="modal-body">
                    <p class="text"> Get ready to play! The clock starts when
                        you select your mode!</p>
                </div>
                <div class="modal-footer">
                    <div id="gameMenu">
                        <button type="button" id="easyGame" onclick="startEasyGame()" class="btn btn-primary btn-block"
                                data-dismiss="modal">Practice Mode
                        </button>
                        <button type="button" id="hardGame" onclick="startHardGame()" class="btn btn-primary btn-block"
                                data-dismiss="modal">Race against the Clock!
                        </button>
                        <a class="btn btn-default btn-block" onclick="yammerLogout()">Logout</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<script>
   var maxRound = 4;
   var trigger = true;
   var score = {{ score }};
   var round = {{ round }};
   var timer;
   var easyGame = 'easy';
   var resized = false;
   var gameMode;
   var correct = 'False';
   var stars = {{ stars|safe }};
   var answer = '{{ answer.id }}';
   var result_cards =  '{{ cards }}';
</script>
<script type="text/javascript"  src="{% static 'js/jquery.jrumble.1.3.min.js' %}"></script>
<script type="text/javascript" src="{% static "js/game.js" %}"></script>

core/templates/custom_game.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <p>
        </p>
    </div>
{% endblock %}

core/templates/game.html
{% extends 'base.html' %}
{% load cards %}

{% block content %}
    <div>
        <p>
        <ul id="cards" class="text-center">
            {% render_cards cards round answer score stars request %}
        </ul>
        </p>
    </div>
{% endblock %}

core/templates/results.html
{% extends 'base.html' %}
{% load replace %}

{% block content %}
    <div class="page-header" id="banner">
        <div class="row">
        </div>
    </div>
    <br>

    <div class="row">
        <ul id="cards" class="text-center clearfix" style="white-space: normal;">
        {% for card in cards %}
            <div id="colleague{{ forloop.counter0 }}" class="resultCards">
                <a href="{{ card.user_url }}" class="thumbnail">
                    <img src='{{ card.mugshot|replace:"/{width}/200"|replace:"/{height}/200"}}'>
                </a>
                <div class="caption">
                {% if not card.wrong %}
                    <div class="resizableText">
                        <a href="{{ card.user_url }}">
                            <span>{{ card.name }}<i class="fa fa-check-circle-o fa-6"></i></span>
                        </a>
                    </div>
                {% elif card.wrong %}
                    <div class="resizableText">
                        <a href="{{ card.user_url }}">
                            <span>{{ card.name }}<i class="fa fa-times-circle-o fa-6"></i></span>
                        </a>
                    </div>
                {% endif %}
                </div>
            </div>
        {% endfor %}
        </ul>
        <div class="text-center inline-block" style="margin-top: 3%">
            <a id="endGame" href="{% url 'core:cards' %}" class="btn btn-primary">Play Again!</a>
            <a id="metrics" href="{% url 'core:metrics' %}" class="btn btn-primary">Check Your Metrics!</a>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script>
    $(document).ready(function () {
        document.title = 'Results';
        //Resize Card Text
        $('.resizableText').textfill({
            minFontPixels: 20,
            maxFontPixels: 45
        });
    });
    </script>
{% endblock %}